### ISSUE TITLE
[feat] 메인 페이지

### ISSUE THREAD

**Issue by NaveOWO** [Today-s-ramen/WEB#1]
## 🌴 작업 브랜치
feat/#1_main-page

## ✅ Todo

- [x] 상단 메인배너 구현
- [x] 소개 레이아웃 구현
- [x] 디테일 소개 레이아웃 구현
- [x] 사용자후기 Slider 구현
- [x] 웰컴쿠폰 & 구독권유 레이아웃 구현
